test: 
   poetry run pytest .
   poetry run mypy .
   poetry run python examples/readme.py
   rm balances.json chart.json store.json

fix:    
   isort . --float-to-top
   black .
   ruff format . # experimetal
   ruff check . --fix
   npx prettier README.md --write

readme:
   echo \"\"\"This file is automatically generated from README.md\"\"\" > examples/readme.py
   cat README.md | codedown python >> examples/readme.py
   poetry run python examples/readme.py
   rm balances.json chart.json store.json
   just fix
