test: 
   poetry run pytest .
   poetry run mypy .
   just readme

fix:    
   just readme
   isort . --float-to-top
   black .
   ruff format . # experimetal
   ruff check . --fix
   npx prettier README.md --write

readme:
   echo \"\"\"This file is automatically generated from README.md\"\"\" > readme.py
   cat README.md | codedown python >> readme.py
   poetry run python readme.py
   rm balances.json chart.json store.json
